name: Publish gem to RubyGems.org

on:
  push:
    branches: main
    paths: lib/**/version.rb
  workflow_dispatch:

jobs:
  publish:
    name: Publish gem to RubyGems.org
    runs-on: ubuntu-latest
    environment: rubygems-publish
    permissions:
      id-token: write
      contents: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - uses: rubygems/release-gem@v1
